#!/usr/bin/env ruby
require 'uri'

# TODO : replace this with a helper running in Tomcat that sets these up, since it's very hard (if not impossible)
# to escape these (NO_PROXY regexp) in the command line.

env = []
{'HTTP_PROXY' => 'http', 'HTTPS_PROXY' => 'https'}.each do |env_var, protocol|
  proxy = ENV[env_var]
  if proxy
    uri = URI.parse(proxy)
    env << "-D#{protocol}.proxyHost=#{uri.host} -D#{protocol}.proxyPort=#{uri.port}"
  end
end

#debug settins for java debugging
jpda = ENV['JPDA']
if jpda
   {'JPDA_TRANSPORT' => 'dt_socket', 'JPDA_ADDRESS' => '8000', 'JPDA_SUSPEND' => 'n'}.each do |env_var, env_val|
       ipda_opts = ENV[env_var]
       ipda_opts = env_val unless ipda_opts
       env << "-D#{env_var}=#{ipda_opts}"
   end
end

puts env.join(' ')
