#!/usr/bin/env ruby
$:.unshift(File.join(File.dirname(__FILE__), '..'))
require 'spec_helper'
require 'client'
require 'fileutils'

TEST_LOCAL_GEM = 'yajl-ruby-0.8.2.gem'
TEST_REMOTE_GEM = 'webmock-1.5.0.gem'
TEST_REMOTE_PIP = 'fluentxml-0.1.1.pip'
TEST_RUNTIME = :ruby18

def check_pkg_in_cache(client, name, type)
  puts "checking for #{name} in cache"
  path = client.get_package_path(name, type, TEST_RUNTIME)
  if path
    puts "found it! =), at #{path}"
  else
    puts "couldn't find it =("
  end
end

def fetch_remote_gem(gem_name)
  url = "http://production.s3.rubygems.org/gems/#{gem_name}"
  `wget --quiet --retry-connrefused --connect-timeout=5 --no-check-certificate #{url}`
end

begin
  enter_test_root
  local_gem_path = File.join Dir.pwd, TEST_LOCAL_GEM
  fetch_remote_gem(TEST_LOCAL_GEM)
  client = VCAP::PackageCache::Client.new

  puts "adding local gem #{local_gem_path} to cache"
  client.add_package(:local, :gem, local_gem_path, TEST_RUNTIME)
  check_pkg_in_cache(client, local_gem_path, :local)

  puts "adding remote gem #{TEST_REMOTE_GEM} to cache"
  client.add_package(:remote, :gem, TEST_REMOTE_GEM, TEST_RUNTIME)
  check_pkg_in_cache(client, TEST_REMOTE_GEM, :remote)
ensure
  exit_test_root
end

