require 'rake'
require 'rubygems/package_task'

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))
require 'vcap/staging/version'

Gem::PackageTask.new(Gem::Specification.load('vcap_staging.gemspec')).define

desc "build gem"
task :build => :gem

namespace 'bundler' do
  task 'install' do
    sh('bundle install')
  end

  environments = %w(test development production)
  environments.each do |env|
    desc "Install gems for #{env}"
    task "install:#{env}" do
      sh("bundle install --local --without #{(environments - [env]).join(' ')}")
    end
  end
end

require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/**/*_spec.rb'
  t.rspec_opts = ['--color', '--format nested']
end

task :default => [:spec]

desc 'Run tests for CI'
task 'ci:spec' => ['ci:setup:rspec', :spec]
