require 'rake'

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))
require 'vcap/staging/version'
require 'ci/reporter/rake/rspec'
ENV['CI_REPORTS'] = File.expand_path('spec/reports', File.dirname(__FILE__))

task :build do
  sh "gem build vcap_staging.gemspec"
end

task :spec => ['bundler:install:test', 'spec:run'] do
  desc 'Prepare bundle and run tests'
end

task 'spec:run' do
  desc 'Run tests (only)'
  sh('cd spec && rake spec')
end

task 'ci:spec' => ["ci:setup:rspec", "spec:run"] do
  desc 'Run tests for CI'
end

namespace 'bundler' do
  task 'install' do
    sh('bundle install')
  end

  environments = %w(test development production)
  environments.each do |env|
    desc "Install gems for #{env}"
    task "install:#{env}" do
      sh("bundle install --local --without #{(environments - [env]).join(' ')}")
    end
  end
end
