require 'spec_helper'
require 'fileutils'
require 'digest/sha1'

describe "Cloud Foundry Tomcat contents fingerprint verification" do

  it "should match the saved fingerprint generated by the Tomcat update script" do
    tomcat_path = File.join(File.dirname(__FILE__),
                            "../../staging/java_web/resources")
    tomcat_zip = File.join(tomcat_path, "tomcat.zip")
    digest = Digest::SHA1.hexdigest(File.read(tomcat_zip))
    fingerprint_hash = {}
    fingerprint_hash['tomcat.zip'] = {
      :size => File.size(tomcat_zip),
      :sha1 => digest
    }

    saved_digest_file = File.join(File.dirname(__FILE__),
                                  "../../../java/tomcat-setup/cf_tomcat.digest")
    saved_fingerprint_hash = YAML.load_file(saved_digest_file)

    fingerprint_hash.should == saved_fingerprint_hash
  end
end
