source :rubygems

gem 'eventmachine'
gem 'nats'
gem 'rake'
gem 'logging', '= 1.5.2'
gem 'yajl-ruby', '>= 0.7.9'

gem 'vcap_common', '~> 1.0.4'
gem 'vcap_logging', '>= 0.1.3'
gem 'vcap_stager_ipc', '= 0.0.2'
gem 'vcap_cloud_controller_ipc'
gem 'vcap_staging', '~> 0.1.35'

# Plugins
gem 'vcap_node_staging_plugin', :require => 'vcap/plugins/staging/node/export', :path => '../plugins/staging/node'

group :test do
  gem 'rspec'
  gem 'sinatra'
  gem 'webmock'
end
