source :rubygems

gem 'eventmachine', :git => 'git://github.com/cloudfoundry/eventmachine.git', :branch => 'release-0.12.11-cf'
gem 'nats'
gem 'rake'
gem 'yajl-ruby', '>= 0.7.9'

gem 'vcap_common', '~> 1.0.8', :git => 'git://github.com/d/vcap-common.git', :ref => 'f6ffe9ad'
gem 'vcap_logging', '>= 0.1.3', :git => 'git://github.com/cloudfoundry/common.git', :ref => 'a07c8ac0'
gem 'vcap_staging', '~> 0.1.51', :git => 'git://github.com/d/vcap-staging.git'

group :test do
  gem 'rspec'
  gem 'sinatra'
  gem 'webmock'
  gem 'ci_reporter'
end
