require 'rubygems'
require 'rake'

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))

task :spec => ['bundler:install:test'] do
  desc 'Run tests'
  sh('cd spec && rake spec')
end

namespace 'bundler' do
  task 'install' do
    sh('bundle install')
  end

  task 'install:test' do
    sh('bundle install --local --without development production')
  end
end
