require 'rubygems'
require 'rake'
require 'rubygems/package_task'

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), 'lib'))

gemspec = Gem::Specification.load('vcap_stager.gemspec')

Gem::PackageTask.new(gemspec).define

task :install => [:package] do
  sh "gem install --no-ri --no-rdoc pkg/#{GEM_NAME}-#{GEM_VERSION}"
end

namespace 'bundler' do
  task 'install' do
    sh('bundle install')
  end

  environments = %w(test development production)
  environments.each do |env|
    desc "Install gems for #{env}"
    task "install:#{env}" do
      sh("bundle install --local --without #{(environments - [env]).join(' ')}")
    end
  end
end

require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/**/*_spec.rb'
  t.rspec_opts = ['--color', '--format nested']
end

desc "Run specs producing results for CI"
task 'ci:spec' => ['ci:setup:rspec', :spec]
