source :rubygems

gem "rake", "~> 0.9.2.2"
gem "sinatra", "~> 1.3.2"
gem "thin", "~> 1.3.1"
gem "vcap_common", "~> 1.0.8"
gem "vcap_logging", ">= 0.1.1"
gem "vcap_package_cache_client", "~> 0.1.8"
gem "warden-client", "~> 0.0.1"

group :test do
  gem 'rspec'
end
