source :rubygems

gem 'rake'
gem 'thin'
gem 'rest-client', '1.6.3'
gem 'async_sinatra'
gem 'em-http-request', '~> 1.0.0.beta.3', :require => 'em-http'
gem 'rack-fiber_pool'

gem 'vcap_common', :path => '../common'
gem 'vcap_logging', '>= 0.1.1'

group :test do
  gem 'rspec'
end
