source 'http://rubygems.org'

# Rails itself
gem 'rails', '~> 3.0.5'
# Message bus
gem 'nats', :require => 'nats/client'

gem 'logging', '>= 1.5.0'

# VCAP common components
gem 'vcap_common', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', :require => ['vcap/logging']
gem 'vcap_staging'
gem 'cf-uaa-client', '>= 0.0.5'

# For queuing staging tasks
gem 'em-hiredis'
gem 'vcap_stager', '~> 0.1.11'

# Databases
gem 'sqlite3'
group :production do
  gem 'pg'
  # Get blocking postgres working for now, try nonblocking drivers when we have more time
  # gem 'postgres-pr', '0.6.3'
  # gem 'em_postgresql', '0.3.0'

  gem 'mysql2', '>= 0.2.6', :require => nil
  # mysql2 includes an EventMachine driver (mysql2/em), don't use em-mysqlplus.
  # To enable, set the :database_env :adapter to 'em_mysql2' in config/cloud_controller.yml
  #
  # Requires a Ruby with Fibers (1.9, rbx, etc), thin (or similar EM-driven appserver), and
  # rack-fiber_pool middleware. Additionally there is a patch applied via plugin if this
  # adapter is selected.
end

# EventMachine and async support
gem 'eventmachine'
gem 'thin'
gem 'em-http-request', '~> 1.0.0.beta.3', :require => 'em-http'
gem 'em-redis', '~> 0.3.0', :require => nil
gem 'rack-fiber_pool', '~> 0.9.1', :require => nil

# Support libraries
gem 'yajl-ruby', '~> 0.8.3'
gem 'nokogiri', '~> 1.4.4'
gem 'bcrypt-ruby', '~> 2.1.4'
gem 'ruby-hmac', '~> 0.4.0', :require => 'hmac-sha1'
gem 'SystemTimer', '~> 1.2', :platforms => :mri_18
gem 'uuidtools', '~> 2.1.2'
gem 'rest-client', '~> 1.6.7'

# rspec-rails is outside the 'test' group in order to consistently provide Rake tasks.
gem 'rspec-rails', '>= 2.4.1'
group :test do
  gem 'rspec', '>= 2.4.0', :require => nil
  gem 'rcov'
  gem 'mocha'
  gem 'ci_reporter'
  gem 'sinatra'  # For service gateway shims
  gem 'delorean'
end

