include_attribute "deployment"
default[:service_broker][:host] = "service-broker"
default[:service_broker][:index] = "0"
default[:service_broker][:token] = "changebrokertoken"
default[:service_broker][:node_timeout] = "5"
