default[:mysql][:server_root_password] = "mysql"
default[:mysql][:server_root_user] = "root"
default[:mysql][:index] = "0"
default[:mysql][:max_db_size] = "20"
default[:mysql][:host] = "localhost"
default[:mysql][:available_storage] = "1024"
default[:mysql][:token] = "changemysqltoken"
