ENV['RAILS_ENV'] = 'test'
ENV['RACK_ENV'] = 'test'
require 'rake'
require 'tempfile'

require 'rubygems'
require 'bundler/setup'

require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

coverage_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "spec_coverage"))
reports_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "spec_reports"))
dump_file = File.join(Dir.tmpdir, "healthmanager.rcov")
ignore_pattern = 'spec,[.]bundle,[/]gems[/]'

ENV['CI_REPORTS'] = reports_dir

desc "Run specs using RCov"
task "spec:rcov" => ["ci:setup:rspec", "spec:rcov_internal", "convert_rcov_to_clover"]

RSpec::Core::RakeTask.new do |t|
  t.pattern = "**/*_spec.rb"
  t.rspec_opts = ["--format", "documentation", "--colour"]
end

desc "Run specs using RCov (internal, use spec:rcov instead)"
RSpec::Core::RakeTask.new('spec:rcov_internal') do |t|
  sh("rm -f #{dump_file}")
  t.pattern = "**/*_spec.rb"
  t.rcov = true
  t.rcov_opts = ['--aggregate', dump_file, '--exclude', ignore_pattern, '--output', coverage_dir]
end

task "convert_rcov_to_clover" do |t|
  analyzer = File.join(File.dirname(__FILE__), "..", "..", "tests", "common", "rcov_analyzer.rb")
  clover_output = File.join(coverage_dir, "clover.xml")
  sh("ruby #{analyzer} #{dump_file} #{ignore_pattern} > #{clover_output}")
  sh("rm -f #{dump_file}")
end
