#!/bin/bash
export GEM_HOME="$PWD/app/rubygems/ruby/1.8"
export GEM_PATH="$PWD/app/rubygems/ruby/1.8"
export PATH="$PWD/app/rubygems/ruby/1.8/bin:/usr/bin:/usr/bin:/bin"
export RACK_ENV="production"
export RAILS_ENV="production"
export RUBYOPT="-I$PWD/ruby -rstdsync"
unset BUNDLE_GEMFILE
mkdir ruby
echo "\$stdout.sync = true" >> ./ruby/stdsync.rb
if [ -f "$PWD/app/config/database.yml" ] ; then
  cd app && %VCAP_LOCAL_RUNTIME% ./rubygems/ruby/1.8/bin/bundle exec %VCAP_LOCAL_RUNTIME% ./rubygems/ruby/1.8/bin/rake db:migrate --trace >>../logs/migration.log 2>> ../logs/migration.log && cd ..;
fi
cd app
%VCAP_LOCAL_RUNTIME% ./rubygems/ruby/1.8/bin/bundle exec %VCAP_LOCAL_RUNTIME% ./rubygems/ruby/1.8/bin/rails server thin $@ > ../logs/stdout.log 2> ../logs/stderr.log &
STARTED=$!
echo "$STARTED" >> ../run.pid
echo "#!/bin/bash" >> ../stop
echo "kill -9 $STARTED" >> ../stop
echo "kill -9 $PPID" >> ../stop
chmod 755 ../stop
wait $STARTED
