#!/usr/bin/env bash
#
# Sets up the environment before invoking the staging_plugin. This executes
# inside the container, so $HOME is /home/vcap.
#
set -o errexit

export PATH=~/bin:$PATH

if [ -f ~/helpers/environment ];
then
  source ~/helpers/environment
fi

exec $@