require 'spec_helper'
require 'fileutils'
require 'digest/sha1'

describe "Cloud Foundry Tomcat contents fingerprint verification" do

  CF_TOMCAT_SHA1_REL_PATH = "../../../java/tomcat-setup/cf-tomcat.zip.sha1"
  it "should match the saved fingerprint generated by the Tomcat update script" do
    tomcat_path = File.join(File.dirname(__FILE__),
                            "../../lib/vcap/staging/plugin/java_web/resources")
    tomcat_zip = File.join(tomcat_path, "tomcat.zip")
    digest = Digest::SHA1.hexdigest(File.read(tomcat_zip))

    saved_digest_file = File.join(File.dirname(__FILE__), CF_TOMCAT_SHA1_REL_PATH)
    saved_digest = IO.readlines(saved_digest_file)[0].split[0]

    digest.should == saved_digest
  end
end
