---
# Deployment
# ----------
deployment:
  name: "dea"

jobs:
  install:
    - dea
  installed:
    - nats_server:
        host: "172.31.4.13"
        port: "4222"
        user: "nats"
        password: "nats"
