#!/usr/bin/env ruby
# Copyright (c) 2009-2011 VMware, Inc.

require 'fcntl'

Dir.foreach("/proc/self/fd") do |fd|
  fd = fd.to_i
  if fd > 2
    # Guess which mode the file was opened in. IO.for_fd will raise
    # Errno::EINVAL if we get this wrong. Not sure of a better way in pure ruby
    # to go about obtaining this information.
    puts "Attempting to close #{fd}"
    closed = false
    for mode in ["r", "w"]
      begin
        io = IO.for_fd(fd, mode)
        io.close
        puts "Closed #{fd}"
        closed = true
        break
      rescue Errno::EINVAL => e
      end
    end
    puts "Failed closing #{fd}" unless closed
  end
end

exec(*ARGV)
