---
deployment:
  name: "mysql1"
jobs:
  install:
    - mysql_node:
        index: "1"
  installed:
    - nats_server:
        host: "172.31.4.13"
        port: "4222"
        user: "nats"
        password: "nats"
