---
deployment:
  name: "rest"
jobs:
  install:
    - nats_server
    - cloud_controller:
        builtin_services:
          - redis
          - mongodb
          - mysql
    - router
    - stager
    - health_manager
    - ccdb
    - redis_node:
        index: "0"
    - redis_gateway
    - mysql_gateway
    - mongodb_node:
        index: "0"
    - mongodb_gateway
