#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), '../lib/vcap/package_cache')))
require 'vcap/package_cache-client/client'
require 'fileutils'

LOCAL_GEM_PATH = '../spec/fixtures/yajl-ruby-0.8.2.gem'
TEST_REMOTE_GEM = 'webmock-1.5.0.gem'
TEST_REMOTE_PIP = 'fluentxml-0.1.1.pip'
TEST_RUNTIME = :ruby18

def check_pkg_in_cache(client, name, type)
  puts "checking for #{name} in cache"
  path = client.get_package_path(name, type, TEST_RUNTIME)
  if path
    puts "found it! =), at #{path}"
  else
    puts "couldn't find it =("
  end
end

begin
  client = VCAP::PackageCacheClient::Client.new

  puts "adding local gem #{LOCAL_GEM_PATH} to cache"
  client.add_package(:local, :gem, LOCAL_GEM_PATH, TEST_RUNTIME)
  check_pkg_in_cache(client, LOCAL_GEM_PATH, :local)

  puts "adding remote gem #{TEST_REMOTE_GEM} to cache"
  client.add_package(:remote, :gem, TEST_REMOTE_GEM, TEST_RUNTIME)
  check_pkg_in_cache(client, TEST_REMOTE_GEM, :remote)
end

