require 'tempfile'

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default, :test)

require 'rake'
require 'rspec'
require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

coverage_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "spec_coverage"))
reports_dir = File.expand_path(File.join(File.dirname(__FILE__), "..", "spec_reports"))
dump_file = File.join(Dir.tmpdir, "dea.rcov")
ignore_pattern = 'spec,[.]bundle,[/]gems[/]'

ENV['CI_REPORTS'] = reports_dir

desc "Run specs using RCov"
task "spec:rcov" => ["ci:setup:rspec", "spec:rcov_internal", "convert_rcov_to_clover"]

RSpec::Core::RakeTask.new do |t|
  t.pattern = "**/*_spec.rb"
  t.rspec_opts = ["--format", "documentation", "--colour"]
end
