source 'http://rubygems.org'
gem 'escape_utils'
gem 'rails', '3.0.5'
gem 'sqlite3'

gem 'devise'
gem 'cancan'
gem 'paperclip'
gem 'searcher', '0.0.5'
gem 'kaminari'
gem 'sinatra'
gem 'nokogiri'

group :test, :development do
  gem 'rspec-rails', '2.0.0'
end

group :test do
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'email_spec', :git => "git://github.com/bmabey/email-spec"
  gem 'launchy'
  gem 'factory_girl'
  gem 'gmail', :git => "git://github.com/radar/gmail"
end

