default[:postgresql][:server_root_password] = "changeme"
default[:postgresql][:server_root_user] = "root"
default[:postgresql][:server_port] = "5432"
default[:postgresql][:version] = "9.0"

default[:postgresql_node][:host] = "localhost"
default[:postgresql_node][:database] = "pg_service"
default[:postgresql_node][:capacity] = "50"
default[:postgresql_node][:max_db_size] = "20"
default[:postgresql_node][:token] = "changepostgresqltoken"
default[:postgresql_node][:index] = "0"
default[:postgresql_node][:timeout] = "10"
