default[:stager][:config_file] = "stager.yml"

default[:vcap_redis][:port] = "5454"
default[:vcap_redis][:password] = "PoIxbL98RWpwBuUJvKNojnpIcRb1ot2"

# Staging
default[:stager][:staging][:grails] = "grails.yml"
default[:stager][:staging][:lift] = "lift.yml"
default[:stager][:staging][:node] = "node.yml"
default[:stager][:staging][:otp_rebar] = "otp_rebar.yml"
default[:stager][:staging][:platform] = "platform.yml"
default[:stager][:staging][:rack] = "rack.yml"
default[:stager][:staging][:rails3] = "rails3.yml"
default[:stager][:staging][:sinatra] = "sinatra.yml"
default[:stager][:staging][:spring] = "spring.yml"
default[:stager][:staging][:java_web] = "java_web.yml"
default[:stager][:staging][:php] = "php.yml"
default[:stager][:staging][:django] = "django.yml"
default[:stager][:staging][:wsgi] = "wsgi.yml"
default[:stager][:staging][:standalone] = "standalone.yml"
default[:stager][:staging][:play] = "play.yml"
