source "http://rubygems.org"

gem "rake"
gem "vcap_common"
gem "vcap_logging"
gem "eventmachine", "0.12.11.cloudfoundry.3"
gem "yajl-ruby"
gem "em-posix-spawn", '> 0.0.1'

group :spec do
  gem "rspec"
  gem "warden-client"
end
