require "rspec/core/rake_task"
require "rspec/core/version"

desc "Run all examples"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = %w[--color --format documentation]
end

desc "Run (or re-run) steps to setup warden"
task :setup, :base_dir do |t, args|
  default_base_dir = File.join(File.dirname(__FILE__), "root/linux/base")
  args.with_defaults(:base_dir => default_base_dir)

  Dir.chdir("src") do
    sh "make clean all"
  end

  sh "sudo -E root/linux/base/setup.sh #{args[:base_dir]}"
end

namespace :warden do
  desc "Run Warden server"
  task :start do
    require "warden/server"
    Warden::Server.setup(:logging => {:level => :debug2})
    Warden::Server.run!
  end
end
