require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "rspec/core/version"

desc "Run all examples"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = %w[--color --format documentation]
end

desc "Run (or re-run) steps to setup warden"
task :setup, :base_dir do |t, args|
  default_base_dir = File.join(File.dirname(__FILE__), "root/linux/base")
  args.with_defaults(:base_dir => default_base_dir)

  unless File.exist?(args[:base_dir])
    abort "ERROR: #{args[:base_dir]} doesn't exist"
  end

  Dir.chdir("src") do
    sh "make clean all"
  end

  to_remove = %w[rootfs union].map {|dir| File.join(args[:base_dir], dir) }
  sh "sudo rm -rf #{to_remove.join(' ')}"
  sh "sudo root/linux/base/setup.sh #{args[:base_dir]}"
end

namespace :warden do
  desc "Run Warden server"
  task :start do
    require "warden/server"
    Warden::Server.setup(:logging => {:level => :debug2})
    Warden::Server.run!
  end
end
