require 'rake'

BASE_DIR = File.expand_path(File.join('..', '..'), __FILE__)
ENV["BUNDLE_GEMFILE"] ||= File.join(BASE_DIR, 'Gemfile')
require 'rubygems'
require 'bundler'
Bundler.setup(:default, :test)

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = '**/*_spec.rb'
  t.rspec_opts = ['--color', '--format nested']
end

task :default => [:spec]
