source "http://rubygems.org"

gem 'eventmachine', :git => 'git://github.com/cloudfoundry/eventmachine.git', :branch => 'release-0.12.11-cf'
gemspec

group :spec do
  gem 'rspec'
  gem 'em-http-request' #, '~> 1.0.0.beta3'
end
