---
listen_port: 3200
logging:
  level: debug
nginx:
  use_nginx: 'false'
  listen_port: 3201
  #listen_socket: /tmp/upload_manager.sock
pid_file: /var/vcap/sys/run/upload_manager.pid
base_dir: /var/vcap.local/upload_manager
purge_resource_pool_on_startup: 'true'
