maintainer       "Uhuru Software"
maintainer_email "support@uhurusoftware.com"
license          "TBD"
description      "Installs/Configures MsSQL Gateway"
long_description "TBD"
version          "0.0.1"
