require 'rake'
require 'ci/reporter/rake/rspec'

desc "Run specs"
task "spec" do |t|
  sh("cd spec && rake spec")
end

desc "Run specs using RCov"
task "spec:rcov" => ["bundler:install:test", "test:spec:rcov"]

desc "Run specs producing results for CI"
task "ci" => ["ci:spec"]

namespace 'bundler' do
  task 'install' do
    sh('bundle install')
  end

  environments = %w(test development production)
  environments.each do |env|
    desc "Install gems for #{env}"
    task "install:#{env}" do
      sh("bundle install --local --without #{(environments - [env]).join(' ')}")
    end
  end
end

namespace :ci do
  task "spec" => ["ci:setup:rspec", "^spec"]
end
