require 'rubygems'
require 'rake'
require 'rspec'
require 'rspec/core/rake_task'
require 'ci/reporter/rake/rspec'

namespace 'bundler' do
  task 'install' do
    sh('bundle install')
  end

  environments = %w(test development production)
  environments.each do |env|
    desc "Install gems for #{env}"
    task "install:#{env}" do
      sh("bundle install --local --without #{(environments - [env]).join(' ')}")
    end
  end
end

namespace :ci do
  desc "Run specs producing results for CI"
  task "spec" => ["ci:setup:rspec", "^spec"]
end


coverage_dir = File.expand_path(File.join(File.dirname(__FILE__), "spec_coverage"))
reports_dir = File.expand_path(File.join(File.dirname(__FILE__), "spec_reports"))

ENV['CI_REPORTS'] = reports_dir

RSpec::Core::RakeTask.new do |t|
  t.pattern = "spec/**/*_spec.rb"
  t.rspec_opts = ["--format", "documentation", "--colour"]
end
