default[:mssql][:server_root_password] = "mysql"
default[:mssql][:server_root_user] = "root"
default[:mssql][:index] = "0"
default[:mssql][:max_db_size] = "20"
default[:mssql][:host] = "localhost"
default[:mssql][:available_storage] = "1024"
default[:mssql][:token] = "changemysqltoken"
