#!/usr/bin/env ruby
require 'uri'

# TODO : Explore replacing this with a helper running in Tomcat that sets these
# up, since it's very hard to escape these (NO_PROXY regexp) in the command line.

def generate_no_proxy_str(str)
  str_elems = str.split(',')
  str_out = str_elems.collect { |raw|
    if raw.strip.start_with?('*', "127", "localhost")
      raw.strip
    else
      wildcard = "*"
      unless raw.strip.start_with?('.')
        wildcard << "."
      end
      "#{wildcard}#{raw.strip}"
    end
  }
  str_out.uniq.join('|')
end

env = []
{'HTTP_PROXY' => 'http', 'HTTPS_PROXY' => 'https'}.each do |env_var, protocol|
  proxy = ENV[env_var]
  if proxy
    uri = URI.parse(proxy)
    env << "-D#{protocol}.proxyHost=#{uri.host} -D#{protocol}.proxyPort=#{uri.port}"
  end
end
no_proxy = ENV['NO_PROXY']
if no_proxy
  no_proxy_str = generate_no_proxy_str(no_proxy)
  env << " -Dhttp.nonProxyHosts=#{no_proxy_str} -Dhttps.nonProxyHosts=#{no_proxy_str}"
end
puts env.join(' ')
